version: '3.3'

services:
  router:
    image: itzg/mc-router:latest
    command: "-debug -in-docker"
    depends_on:
      - minecraft-survival
      - minecraft-creative
    ports:
      - "${SERVER_PORT}:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
# MINECRAFT SERVERS:
  minecraft-survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    volumes:
      - ${SURVIVAL_DIR}:/data
    ports:
      - ${SURVIVAL_PORT}:25565
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      OPS: ${OP_NAME}
      MOTD: "Survival"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "${OP_NAME}"
      VERSION: "${SERVER_VERSION}"
      DEBUG: "TRUE"
    labels:
      mc-router.host: "survival.localhost"
      mc-router.default: true
    restart: unless-stopped

  minecraft-creative:
    container_name: minecraft-creative
    image: itzg/minecraft-server
    volumes:
      - ${CREATIVE_DIR}:/data
    ports:
      - ${CREATIVE_PORT}:25565
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      OPS: ${OP_NAME}
      MOTD: "Creative"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "${OP_NAME}"
      VERSION: "${SERVER_VERSION}"
      DEBUG: "TRUE"
    labels:
      mc-router.host: "creative.localhost"
    restart: unless-stopped
