version: '3.3'

services:
  proxy:
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
    ports:
      - "${SERVER_PORT}:25577"
    volumes:
      - "${PROXY_DIR}:/server"

  minecraft-survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    volumes:
      - ${SURVIVAL_DIR}:/data
    ports:
      - ${SURVIVAL_PORT}:25565
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      OPS: ${OP_NAME}
      ONLINE_MODE: "FALSE"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "kijenasa"
      VERSION: "${SERVER_VERSION}"
      DEBUG: "TRUE"
    restart: unless-stopped

  minecraft-creative:
    container_name: minecraft-creative
    image: itzg/minecraft-server
    volumes:
      - ${CREATIVE_DIR}:/data
    ports:
      - ${CREATIVE_PORT}:25565
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      OPS: ${OP_NAME}
      ONLINE_MODE: "FALSE"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: "${WHITELIST}"
      VERSION: "${SERVER_VERSION}"
      DEBUG: "TRUE"
    restart: unless-stopped
